spring.application.name=aopApp

spring.datasource.url=jdbc:postgresql://localhost:5432/aopdb
spring.datasource.username=postgres
spring.datasource.password=Nitu@123
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8084